-- Generated by pywal from None
-- Consumed by ~/.config/hypr/conf/colors.lua
return {
    background = "rgb(100a16)",
    foreground = "rgb(dedeee)",
    cursor     = "rgb(dedeee)",
    color0  = "rgb(100a16)",
    color1  = "rgb(5630A6)",
    color2  = "rgb(715295)",
    color3  = "rgb(956DA9)",
    color4  = "rgb(B7A4C6)",
    color5  = "rgb(CFA0D4)",
    color6  = "rgb(FBB3FB)",
    color7  = "rgb(dedeee)",
    color8  = "rgb(9b9ba6)",
    color9  = "rgb(5630A6)",
    color10 = "rgb(715295)",
    color11 = "rgb(956DA9)",
    color12 = "rgb(B7A4C6)",
    color13 = "rgb(CFA0D4)",
    color14 = "rgb(FBB3FB)",
    color15 = "rgb(dedeee)",
    -- Pre-composed with alpha so the inactive border stays dim regardless
    -- of how bright pywal's color8 happens to be for a given wallpaper.
    border_active_a = "rgba(CFA0D4ee)",
    border_active_b = "rgba(FBB3FBee)",
    border_inactive = "rgba(9b9ba655)",
    shadow          = "rgba(100a1699)",
}
