# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#100a16'
foreground='#dedeee'
cursor='#dedeee'

# Colors
color0='#100a16'
color1='#5630A6'
color2='#715295'
color3='#956DA9'
color4='#B7A4C6'
color5='#CFA0D4'
color6='#FBB3FB'
color7='#dedeee'
color8='#9b9ba6'
color9='#5630A6'
color10='#715295'
color11='#956DA9'
color12='#B7A4C6'
color13='#CFA0D4'
color14='#FBB3FB'
color15='#dedeee'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
